sonar.projectKey=EmployeePayroll
sonar.host.url=http://localhost:9000
sonar.token=sqa_40cd858576eee184d7eeae644f6f00567a5f7d55
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/__tests__/**, **/*.test.js, **/*.test.jsx, **/*.spec.js, **/*.spec.jsx
sonar.coverage.exclusions=**/__tests__/**, **/*.test.js, **/*.test.jsx, **/*.spec.js, **/*.spec.jsx, src/app.jsx, src/main.jsx, src/App.jsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info